### ISSUE TITLE
Continuing unwanted FX from missile launchers in new version

### ISSUE THREAD

**Issue by SpannerMonkey** [jrodrigv/DestructionEffects#6]
The latest edition of DFX causes flame and smoke effects to be  produced from missile turrets and launchers  that  use NODE to set the missile attachment points  After much investigation and elimination of possible causes, the only conclusion left is that it is the breaking of these  NODE type nodes that generate the FX
Missile launchers/rails (such as those in BDA) that use the old method of node placement are unaffected  BDA seems quite happy to use either or both methods of node placement , and function is identical.

`Old nodes
node_stack_missile1 = 0.8587526, 0.7144908, -2.094282, 0, 0, 1, 0
`
`New style
	NODE
{
name = Node2
transform = Node2
size = 0
method = FIXED_JOINT 
}`
Is there a way to exempt NODE type nodes?   Although many parts now define their stack attachments this way(99% of my parts) and excluding them may/would result in a situation where old parts have joint break FX while newer ones don't

As mentioned previously I still feel the best arrangement would be some way to assign or not FX to parts rather than the blanket application now used
I would of course be happy with any situation which simply stopped the launchers unwanted FX

Example below is a fully fitted Bradley turret firing a BDAc TOW missile.  You may also note that  the size of the effect is also way out of proportion to the node size broken( size0)
![screenshot169](https://cloud.githubusercontent.com/assets/8117008/24777146/f28ba058-1b1b-11e7-8b76-8a03557a02e4.png)

**Comment by gomker** [comment]
Has this been fixed? I noticed after I merged latest release It not longer did this with missile rails

**Comment by SpannerMonkey** [comment]
I will retest

**Comment by jrodrigv** [comment]
I will find a fix for this, if it still happening. Let me know the outcome of the testing @SpannerMonkey :)

**Comment by SpannerMonkey** [comment]
Tested now all turrets previously affected , on the whole it is much improved and rail type turrets and VLS perform without issue although I am still having an issue with the turret featured in the video above. 
  
However the combination of nodes is different in that case ,  in that the turret fires the stock BDAc TOW missile which has traditional cfg placed  nodes, and the turret has  unity placed NODE type nodes, while all the other now unaffected missiles also have NODE type nodes,  

Can supply test version if required

**Comment by gomker** [comment]
I was thinking that we should implement a section in the config file that has a list by part name or tag that we could specify instead of using static lists like here

https://github.com/jrodrigv/DestructionEffects/blob/master/FlamingJoints.cs#L17
https://github.com/jrodrigv/DestructionEffects/blob/master/FlamingJoints.cs#L115

This way we could update as needed what parts need to be triggered or ignored

**Comment by SpannerMonkey** [comment]
I did have a poke around that and I (we) couldn't get the statics to do what we wanted,  even with ignore set the effects still occurred, and i see the code still has my footprints all over it.  
 I'm very happy with the improvements made to date and as gomker mentions,  with a notable exception they are pretty much sorted. The Brad and tow launcher I feel are very much edge case, as all but one of the combi turrets in existence are mine from one mod or other, it's not something that will ever happen to most players (niche parts in a niche market) .  Furthers refinements would be very nice. If it's worth the effort for one instance,
